Remove num derive
DanielT/autosar-xsd-mangler pull request #1
Opened 2024-12-03 08:50 UTC by shahn

One commit changes Double to Float in the generated code, please check why that was necessary. Maybe this crate and what is published in autosar-data-specification got out of sync in some way?

2024-12-03 11:21 UTC, DanielT commented
Yes, I knew about the missing double to float renaming. I just came across it a few days ago when I added support for R24-11, but I forgot to push my branch with the fix. Oops.

2024-12-03 12:06 UTC, shahn commented
No worries of course :) I just didn't know if maybe more had changed.

2024-12-14 08:03 UTC, DanielT commented
Hi, do you want to submit a fixed pull request?

2024-12-14 10:55 UTC, shahn commented
Yes, but I am confused. Do you mean with the float renaming patch removed? Or what else would there be to fix?

2024-12-14 11:39 UTC, DanielT commented
No, i mean the incorrect numbers, as noted in the review comment.

2024-12-14 12:40 UTC, shahn commented
Did you "finish" the review? I do not see any review comments, sorry. Of course I am very happy to fix it

2024-12-14 13:21 UTC, DanielT requested changes

2024-12-14 13:21 UTC, DanielT commented on src/generator/xsd_versions.rs
> +            1 << idx, xsd_file_info.ident
This code is incorrect, you need the {:x}. As it is, it would generate 0x<integer>, e.g. "0x256" instead of 0x100.

2024-12-14 13:21 UTC, DanielT commented on src/generator/xsd_versions.rs
> +            1 << idx, xsd_file_info.ident
Indeed, after running your code, I got the following:
```
    #[inline]
    fn from_u64(n: u64) -> Option<Self> {
        match n {
            0x1 => Some(Self::Autosar_4_0_1),
            0x2 => Some(Self::Autosar_4_0_2),
            0x4 => Some(Self::Autosar_4_0_3),
            0x8 => Some(Self::Autosar_4_1_1),
            0x16 => Some(Self::Autosar_4_1_2),
            0x32 => Some(Self::Autosar_4_1_3),
            0x64 => Some(Self::Autosar_4_2_1),
            0x128 => Some(Self::Autosar_4_2_2),
            0x256 => Some(Self::Autosar_4_3_0),
            0x512 => Some(Self::Autosar_00042),
            0x1024 => Some(Self::Autosar_00043),
            0x2048 => Some(Self::Autosar_00044),
            0x4096 => Some(Self::Autosar_00045),
            0x8192 => Some(Self::Autosar_00046),
            0x16384 => Some(Self::Autosar_00047),
            0x32768 => Some(Self::Autosar_00048),
            0x65536 => Some(Self::Autosar_00049),
            0x131072 => Some(Self::Autosar_00050),
            0x262144 => Some(Self::Autosar_00051),
            0x524288 => Some(Self::Autosar_00052),
            0x1048576 => Some(Self::Autosar_00053),

            _ => None,
        }
    }
```

2024-12-14 13:21 UTC, DanielT commented
Yes, you're correct.
I just submitted the review, which was in the draft state

2024-12-14 14:06 UTC, shahn commented on src/generator/xsd_versions.rs
> +            1 << idx, xsd_file_info.ident
Thanks and nice catch

2024-12-14 14:07 UTC, shahn commented
Updated, thanks!

2024-12-14 14:48 UTC, merged